---
deployment:
  tasks:
    - echo "Starting Vite React app deployment..."
    - echo "Step 1: Installing dependencies."
    - npm install
    - echo "Step 2: Building the Vite app."
    - npm run build
    - echo "Step 3: Replacing old files with new ones in public_html."
    - cp -ru dist/* /home/applinkatik/public_html/
    - echo "Deployment completed successfully!"
