name: deploy
deployment:
  tasks:
    - echo "Starting Vite React app deployment..."
    - echo "Step 1: Installing dependencies."
    - npm install || { echo "Dependency installation failed!"; exit 1; }
    - echo "Dependencies installed."
    - echo "Step 2: Building the Vite app."
    - npm run build || { echo "Build failed!"; exit 1; }
    - echo "Build complete."
    - echo "Step 3: Replacing old files with new ones in public_html."
    - cp -ru dist/* /home/applinkatik/public_html/ || { echo "File replacement failed!"; exit 1; }
    - echo "Files replaced."
    - echo "Deployment completed successfully!"
